"""Add remaining models

Revision ID: 665ac07a4416
Revises: 001_supabase_initial_schema
Create Date: 2026-09-17 12:16:10.352509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665ac07a4416'
down_revision: Union[str, Sequence[str], None] = '001_supabase_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('co2_factor', sa.Float(), nullable=True),
    sa.Column('ch4_factor', sa.Float(), nullable=True),
    sa.Column('n2o_factor', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.String(length=50), nullable=True),
    sa.Column('valid_to', sa.String(length=50), nullable=True),
    sa.Column('methodology', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emission_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emission_factors_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_emission_factors_id'), ['id'], unique=False)

    op.create_table('frameworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frameworks_id'), ['id'], unique=False)

    op.create_table('esg_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esg_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esg_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esg_metrics_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esg_metrics_period'), ['period'], unique=False)

    op.create_table('esg_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('environmental_score', sa.Float(), nullable=False),
    sa.Column('social_score', sa.Float(), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=False),
    sa.Column('methodology_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esg_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esg_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esg_scores_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esg_scores_period'), ['period'], unique=False)

    op.create_table('framework_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('requirement_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('required_data', sa.String(length=1024), nullable=True),
    sa.Column('required_evidence', sa.String(length=1024), nullable=True),
    sa.Column('applicability', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('framework_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_requirements_framework_id'), ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_requirements_id'), ['id'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('extraction_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('methodology_version', sa.String(length=50), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_organization_id'), ['organization_id'], unique=False)

    op.create_table('compliance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_document_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['framework_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('scope1_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('activity_value', sa.Float(), nullable=False),
    sa.Column('activity_unit', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=True),
    sa.Column('co2e', sa.Float(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope1_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope1_records_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope1_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope1_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope1_records_period'), ['period'], unique=False)

    op.create_table('scope2_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('activity_value', sa.Float(), nullable=False),
    sa.Column('activity_unit', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=True),
    sa.Column('co2e', sa.Float(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope2_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope2_records_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope2_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope2_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope2_records_period'), ['period'], unique=False)

    op.create_table('scope3_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('activity_value', sa.Float(), nullable=False),
    sa.Column('activity_unit', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=True),
    sa.Column('co2e', sa.Float(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope3_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope3_records_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope3_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope3_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope3_records_period'), ['period'], unique=False)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    with op.batch_alter_table('scope3_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope3_records_period'))
        batch_op.drop_index(batch_op.f('ix_scope3_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scope3_records_id'))
        batch_op.drop_index(batch_op.f('ix_scope3_records_facility_id'))

    op.drop_table('scope3_records')
    with op.batch_alter_table('scope2_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope2_records_period'))
        batch_op.drop_index(batch_op.f('ix_scope2_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scope2_records_id'))
        batch_op.drop_index(batch_op.f('ix_scope2_records_facility_id'))

    op.drop_table('scope2_records')
    with op.batch_alter_table('scope1_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope1_records_period'))
        batch_op.drop_index(batch_op.f('ix_scope1_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scope1_records_id'))
        batch_op.drop_index(batch_op.f('ix_scope1_records_facility_id'))

    op.drop_table('scope1_records')
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_records_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_id'))

    op.drop_table('compliance_records')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_id'))

    op.drop_table('risk_events')
    with op.batch_alter_table('framework_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_requirements_id'))
        batch_op.drop_index(batch_op.f('ix_framework_requirements_framework_id'))

    op.drop_table('framework_requirements')
    with op.batch_alter_table('esg_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esg_scores_period'))
        batch_op.drop_index(batch_op.f('ix_esg_scores_organization_id'))
        batch_op.drop_index(batch_op.f('ix_esg_scores_id'))

    op.drop_table('esg_scores')
    with op.batch_alter_table('esg_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esg_metrics_period'))
        batch_op.drop_index(batch_op.f('ix_esg_metrics_organization_id'))
        batch_op.drop_index(batch_op.f('ix_esg_metrics_id'))

    op.drop_table('esg_metrics')
    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frameworks_id'))

    op.drop_table('frameworks')
    with op.batch_alter_table('emission_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emission_factors_id'))
        batch_op.drop_index(batch_op.f('ix_emission_factors_category'))

    op.drop_table('emission_factors')
    # ### end Alembic commands ###
